name: Create Release
on:
  repository_dispatch:
    types: [tests-passed]

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Checkout specific commit
        run: |
          git checkout ${{ github.event.client_payload.sha }}
      
      - name: Create tag
        run: |
          git tag "${{ github.event.client_payload.version }}"
          git push origin "${{ github.event.client_payload.version }}"
      
      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "${{ github.event.client_payload.version }}" \
            --target ${{ github.event.client_payload.sha }} \
            --draft \
            --generate-notes
      
#      is this actually needed?
#      - name: Set up Ruby
#        uses: ruby/setup-ruby@v1
#        with:
#          ruby-version: '3.0'
      
      - name: Install CocoaPods
        run: gem install cocoapods

      - name: Pod spec lint
        run: pod spec lint --allow-warnings

#      - name: Pod trunk push
#        run: pod trunk push --allow-warnings
#        env:
#          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
