name: Create CocoaPod

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      commit_sha:
        description: 'Commit hash to checkout and push to CocoaPods'
        required: true
        type: string

jobs:
  push-to-cocoapods:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: fix bad pod
        run: pod trunk delete Helium 2.0.0
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
