name: Create CocoaPod

on:
  release:
    types: [released]
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name to checkout and push to CocoaPods'
        required: true
        type: string

jobs:
  push-to-cocoapods:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Checkout specific tag (for manual trigger)
        if: github.event_name == 'workflow_dispatch'
        run: |
          git fetch --all --tags
          git checkout refs/tags/${{ github.event.inputs.tag_name }}
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
      
      - name: Install CocoaPods
        run: gem install cocoapods

      - name: Pod spec lint
        run: pod spec lint --allow-warnings

      - name: Pod trunk push
        run: pod trunk push --allow-warnings
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
