name: Sync Release Version to SDK

on:
  release:
    types: [published, prereleased]

jobs:
  update-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.target_commitish }}
          fetch-depth: 0
          
      - name: Get release version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
        
      - name: Update version in BuildConstants.swift
        run: |
          VERSION=$(echo "${{ steps.get_version.outputs.VERSION }}" | sed 's/^v//')
          sed -i "s/static let version = \".*\"/static let version = \"${VERSION}\"/" Sources/HeliumCore/BuildConstants.swift
          
      - name: Commit and push changes
        id: commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add Sources/HeliumCore/BuildConstants.swift
          git commit -m "chore: update version to ${{ steps.get_version.outputs.VERSION }}"
          git push
          echo "commit=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
          
      - name: Delete and recreate tag
        run: |
          git push --delete origin ${{ steps.get_version.outputs.VERSION }} || true
          git tag -d ${{ steps.get_version.outputs.VERSION }} || true
          git tag ${{ steps.get_version.outputs.VERSION }} ${{ steps.commit.outputs.commit }}
          git push origin ${{ steps.get_version.outputs.VERSION }}
          
      - name: Update release to point to new commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release edit ${{ steps.get_version.outputs.VERSION }} \
            --target ${{ steps.commit.outputs.commit }} \
            --draft=false \
            --prerelease=${{ github.event.release.prerelease }} \
            --latest=${{ !github.event.release.prerelease }}