name: Sync Release Version to SDK

on:
  release:
    types: [published]

jobs:
  update-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.target_commitish }}
          
      - name: Get release version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
        
      - name: Update version in BuildConstants.swift
        run: |
          VERSION=$(echo "${{ steps.get_version.outputs.VERSION }}" | sed 's/^v//')
          sed -i "s/static let version = \".*\"/static let version = \"${VERSION}\"/" Sources/HeliumCore/BuildConstants.swift
          
      - name: Commit and push changes
        id: commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add Sources/HeliumCore/BuildConstants.swift
          git commit -m "chore: update version to ${{ steps.get_version.outputs.VERSION }}"
          git push
          echo "commit=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
          
      - name: Update release to point to new commit
        run: |
          gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"
          gh release edit ${{ steps.get_version.outputs.VERSION }} --target ${{ steps.commit.outputs.commit }}